// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue[T river.JobArgs](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue[T] {
	mock := &MockQueue[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue[T river.JobArgs] struct {
	mock.Mock
}

type MockQueue_Expecter[T river.JobArgs] struct {
	mock *mock.Mock
}

func (_m *MockQueue[T]) EXPECT() *MockQueue_Expecter[T] {
	return &MockQueue_Expecter[T]{mock: &_m.Mock}
}

// CancelJobs provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) CancelJobs(ctx context.Context, ids ...int64) error {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CancelJobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) error); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_CancelJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobs'
type MockQueue_CancelJobs_Call[T river.JobArgs] struct {
	*mock.Call
}

// CancelJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...int64
func (_e *MockQueue_Expecter[T]) CancelJobs(ctx interface{}, ids ...interface{}) *MockQueue_CancelJobs_Call[T] {
	return &MockQueue_CancelJobs_Call[T]{Call: _e.mock.On("CancelJobs",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockQueue_CancelJobs_Call[T]) Run(run func(ctx context.Context, ids ...int64)) *MockQueue_CancelJobs_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		var variadicArgs []int64
		if len(args) > 1 {
			variadicArgs = args[1].([]int64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQueue_CancelJobs_Call[T]) Return(err error) *MockQueue_CancelJobs_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_CancelJobs_Call[T]) RunAndReturn(run func(ctx context.Context, ids ...int64) error) *MockQueue_CancelJobs_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteJobs provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) DeleteJobs(ctx context.Context, ids ...int64) error {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) error); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_DeleteJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobs'
type MockQueue_DeleteJobs_Call[T river.JobArgs] struct {
	*mock.Call
}

// DeleteJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...int64
func (_e *MockQueue_Expecter[T]) DeleteJobs(ctx interface{}, ids ...interface{}) *MockQueue_DeleteJobs_Call[T] {
	return &MockQueue_DeleteJobs_Call[T]{Call: _e.mock.On("DeleteJobs",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockQueue_DeleteJobs_Call[T]) Run(run func(ctx context.Context, ids ...int64)) *MockQueue_DeleteJobs_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		var variadicArgs []int64
		if len(args) > 1 {
			variadicArgs = args[1].([]int64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQueue_DeleteJobs_Call[T]) Return(err error) *MockQueue_DeleteJobs_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_DeleteJobs_Call[T]) RunAndReturn(run func(ctx context.Context, ids ...int64) error) *MockQueue_DeleteJobs_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FetchJob provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) FetchJob(ctx context.Context, id int64) (*rivertype.JobRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchJob")
	}

	var r0 *rivertype.JobRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rivertype.JobRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rivertype.JobRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rivertype.JobRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_FetchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchJob'
type MockQueue_FetchJob_Call[T river.JobArgs] struct {
	*mock.Call
}

// FetchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQueue_Expecter[T]) FetchJob(ctx interface{}, id interface{}) *MockQueue_FetchJob_Call[T] {
	return &MockQueue_FetchJob_Call[T]{Call: _e.mock.On("FetchJob", ctx, id)}
}

func (_c *MockQueue_FetchJob_Call[T]) Run(run func(ctx context.Context, id int64)) *MockQueue_FetchJob_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_FetchJob_Call[T]) Return(jobRow *rivertype.JobRow, err error) *MockQueue_FetchJob_Call[T] {
	_c.Call.Return(jobRow, err)
	return _c
}

func (_c *MockQueue_FetchJob_Call[T]) RunAndReturn(run func(ctx context.Context, id int64) (*rivertype.JobRow, error)) *MockQueue_FetchJob_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FetchJobs provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) FetchJobs(ctx context.Context, ids ...int64) ([]*rivertype.JobRow, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FetchJobs")
	}

	var r0 []*rivertype.JobRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) ([]*rivertype.JobRow, error)); ok {
		return returnFunc(ctx, ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) []*rivertype.JobRow); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rivertype.JobRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...int64) error); ok {
		r1 = returnFunc(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_FetchJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchJobs'
type MockQueue_FetchJobs_Call[T river.JobArgs] struct {
	*mock.Call
}

// FetchJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...int64
func (_e *MockQueue_Expecter[T]) FetchJobs(ctx interface{}, ids ...interface{}) *MockQueue_FetchJobs_Call[T] {
	return &MockQueue_FetchJobs_Call[T]{Call: _e.mock.On("FetchJobs",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockQueue_FetchJobs_Call[T]) Run(run func(ctx context.Context, ids ...int64)) *MockQueue_FetchJobs_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		var variadicArgs []int64
		if len(args) > 1 {
			variadicArgs = args[1].([]int64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQueue_FetchJobs_Call[T]) Return(jobRows []*rivertype.JobRow, err error) *MockQueue_FetchJobs_Call[T] {
	_c.Call.Return(jobRows, err)
	return _c
}

func (_c *MockQueue_FetchJobs_Call[T]) RunAndReturn(run func(ctx context.Context, ids ...int64) ([]*rivertype.JobRow, error)) *MockQueue_FetchJobs_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) Insert(ctx context.Context, args T, opts ...*river.InsertOpts) (*rivertype.JobInsertResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, args, opts)
	} else {
		tmpRet = _mock.Called(ctx, args)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *rivertype.JobInsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, ...*river.InsertOpts) (*rivertype.JobInsertResult, error)); ok {
		return returnFunc(ctx, args, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, ...*river.InsertOpts) *rivertype.JobInsertResult); ok {
		r0 = returnFunc(ctx, args, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rivertype.JobInsertResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T, ...*river.InsertOpts) error); ok {
		r1 = returnFunc(ctx, args, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockQueue_Insert_Call[T river.JobArgs] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - args T
//   - opts ...*river.InsertOpts
func (_e *MockQueue_Expecter[T]) Insert(ctx interface{}, args interface{}, opts ...interface{}) *MockQueue_Insert_Call[T] {
	return &MockQueue_Insert_Call[T]{Call: _e.mock.On("Insert",
		append([]interface{}{ctx, args}, opts...)...)}
}

func (_c *MockQueue_Insert_Call[T]) Run(run func(ctx context.Context, args T, opts ...*river.InsertOpts)) *MockQueue_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 []*river.InsertOpts
		var variadicArgs []*river.InsertOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*river.InsertOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueue_Insert_Call[T]) Return(jobInsertResult *rivertype.JobInsertResult, err error) *MockQueue_Insert_Call[T] {
	_c.Call.Return(jobInsertResult, err)
	return _c
}

func (_c *MockQueue_Insert_Call[T]) RunAndReturn(run func(ctx context.Context, args T, opts ...*river.InsertOpts) (*rivertype.JobInsertResult, error)) *MockQueue_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) InsertMany(ctx context.Context, args []T, opts ...*river.InsertOpts) ([]*rivertype.JobInsertResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, args, opts)
	} else {
		tmpRet = _mock.Called(ctx, args)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []*rivertype.JobInsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T, ...*river.InsertOpts) ([]*rivertype.JobInsertResult, error)); ok {
		return returnFunc(ctx, args, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T, ...*river.InsertOpts) []*rivertype.JobInsertResult); ok {
		r0 = returnFunc(ctx, args, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rivertype.JobInsertResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []T, ...*river.InsertOpts) error); ok {
		r1 = returnFunc(ctx, args, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockQueue_InsertMany_Call[T river.JobArgs] struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - args []T
//   - opts ...*river.InsertOpts
func (_e *MockQueue_Expecter[T]) InsertMany(ctx interface{}, args interface{}, opts ...interface{}) *MockQueue_InsertMany_Call[T] {
	return &MockQueue_InsertMany_Call[T]{Call: _e.mock.On("InsertMany",
		append([]interface{}{ctx, args}, opts...)...)}
}

func (_c *MockQueue_InsertMany_Call[T]) Run(run func(ctx context.Context, args []T, opts ...*river.InsertOpts)) *MockQueue_InsertMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		var arg2 []*river.InsertOpts
		var variadicArgs []*river.InsertOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*river.InsertOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueue_InsertMany_Call[T]) Return(jobInsertResults []*rivertype.JobInsertResult, err error) *MockQueue_InsertMany_Call[T] {
	_c.Call.Return(jobInsertResults, err)
	return _c
}

func (_c *MockQueue_InsertMany_Call[T]) RunAndReturn(run func(ctx context.Context, args []T, opts ...*river.InsertOpts) ([]*rivertype.JobInsertResult, error)) *MockQueue_InsertMany_Call[T] {
	_c.Call.Return(run)
	return _c
}
