template: testify
formatter: gofmt
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
packages:
  github.com/defany/goblin/riverx:
    config:
      all: true
